// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TESTE1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TESTE1', async function() {
    await driver.get("http://publicazo.insprak.com/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.id("search")).click()
    await driver.findElement(By.id("search")).sendKeys("teste")
    await driver.findElement(By.id("search")).sendKeys(Key.ENTER)
    await driver.findElement(By.linkText("Aulas de Teste de Software")).click()
    await driver.findElement(By.linkText("Aulas de informática em domicílio")).click()
    await driver.findElement(By.css(".col-md-4:nth-child(5) .panel-body")).click()
    await driver.findElement(By.linkText("Aulas de matemática")).click()
    await driver.findElement(By.css(".col-md-4:nth-child(7) a")).click()
  })
})
